'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SimpleWebReportCatalog

    Partial Public Class [Default]

        '''<summary>
        '''CatalogForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CatalogForm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ReportsList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportsList As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''AccessDataSource1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AccessDataSource1 As Global.System.Web.UI.WebControls.AccessDataSource

        '''<summary>
        '''EditButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DeleteButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DeleteButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''NewReportButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NewReportButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ReportIDTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportIDTextBox As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
